### ISSUE TITLE
Looks like this is a dead project? 

### ISSUE THREAD

**Issue by HackyPenguin** [abysl/AssetManager#1]
Is this a dead project? The Mac asset manager is unable to install, I am also unable to build from source missing some dependency's

* What went wrong:
Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.6.10'] was not found in any of the following sources:

```
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.6.10')
```
Is this expected to work? I notice there has been no movement for over a year so was unsure if it's worth trying to get working?

trying to run the pre-compiled.dmg gives the this can't be opened because its damaged message. 

Mac version: Mac  14.1.1 (23B81)

**Comment by HackyPenguin** [comment]
Update, I was able to get it to start up with ./gradlew run however receive this error when using the itch api call to download things: 

```

xception in thread "DefaultDispatcher-worker-3" kotlinx.serialization.MissingFieldException: Field 'short_text' is required for type with serial name 'com.abysl.itch.model.ItchGame', but it was missing
        at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
        at com.abysl.itch.model.ItchGame.<init>(ItchGame.kt:5)
        at com.abysl.itch.model.ItchGame.<init>(ItchGame.kt)
        at com.abysl.itch.model.ItchGame$$serializer.deserialize(ItchGame.kt:5)
        at com.abysl.itch.model.ItchGame$$serializer.deserialize(ItchGame.kt:5)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
        at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
        at com.abysl.itch.Itch.getAssets(Itch.kt:165)
        at com.abysl.itch.Itch$getAssets$1.invokeSuspend(Itch.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.abysl.assetmanager.services.AssetImportService$importItchAssets$1.invokeSuspend(AssetImportService.kt:20)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by abueide** [comment]
@HackyPenguin its kinda dead, kind of been planning on a rewrite as the current version is not super useful / buggy when it comes to searching assets through the gui, but it should still work well just for exporting and unzipping assets automatically to your filesystem. I can take a look at it this weekend and get it working again if that's what you're looking for.
